In [1]:
import numpy as np

In [2]:
mylist=[1,2,3,4]
type(mylist)

list

In [4]:
n_list=np.array(mylist) # conversion of list to an array
type(n_list)

numpy.ndarray

In [6]:
range=np.arange(10)
print(range)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
line_space=np.linspace(0,10,3) #3 is the total no you want bw 0 to 10 with evenly sequenced
print(line_space)

[ 0.  5. 10.]


In [15]:
r=np.random.rand(2,2) # generates random number in range of 0-1 in the 2X2 matrix
r

array([[0.61976143, 0.17704075],
       [0.18443877, 0.14015802]])

In [20]:
arr=np.array([12,23,44,322,12])
print(np.max(arr))
print(np.min(arr))

322
12
