In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
fd=pd.read_csv('salary.csv')
fd.head()

YearExperience   Salary
0               1    30000
1               2    60000
2               3    90000
3               4  1200000
4               5  1500000

In [6]:
x=fd.iloc[:,:-1].values
x

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
y=fd.iloc[:,-1].values
y


array([  30000,   60000,   90000, 1200000, 1500000])

In [8]:
#train Test Split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)


In [10]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred=regression.predict(x_test)

In [13]:
regression.score(x,y)

0.7786988672516744

In [14]:
regression.predict([[6]])

array([2070000.])

In [17]:
plt.plot(x_train,y_train)
plt.scatter(x_train,regression.predict(x_train))
plt.show()